import { MigrationInterface, QueryRunner } from 'typeorm';

export class TBGRUPO1693504310699 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
    CREATE TABLE TB_GRUPO (
      CO_GRUPO VARCHAR(2) PRIMARY KEY,
      NO_GRUPO VARCHAR(100),
      DS_GRUPO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    CREATE TABLE TB_SUBGRUPO (
      CO_GRUPO VARCHAR(2),
      CO_SUB_GRUPO VARCHAR(2) PRIMARY KEY,
      NO_SUB_GRUPO VARCHAR(100),
      DS_SUB_GRUPO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );

    ALTER TABLE TB_SUBGRUPO ADD FOREIGN KEY (CO_GRUPO) REFERENCES TB_GRUPO (CO_GRUPO);
    
    CREATE TABLE TB_FORMA_ORGANIZACAO (
      CO_GRUPO VARCHAR(2),
      CO_SUB_GRUPO VARCHAR(2),
      CO_FORMA_ORGANIZACAO VARCHAR(2),
      NO_FORMA_ORGANIZACAO VARCHAR(100),
      DS_FORMA_ORGANIZACAO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );

    ALTER TABLE TB_FORMA_ORGANIZACAO ADD FOREIGN KEY (CO_GRUPO) REFERENCES TB_GRUPO (CO_GRUPO);
      
    ALTER TABLE TB_FORMA_ORGANIZACAO ADD FOREIGN KEY (CO_SUB_GRUPO) REFERENCES TB_SUBGRUPO (CO_SUB_GRUPO);
    
    
    CREATE TABLE TB_PROCEDIMENTO (
      CO_PROCEDIMENTO VARCHAR(10) PRIMARY KEY,
      NO_PROCEDIMENTO VARCHAR(100),
      DS_PROCEDIMENTO VARCHAR(800),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_COMPOSICAO_PROCEDIMENTO (
      CO_PROCEDIMENTO VARCHAR(10),
      TP_COMPLEXIDADE VARCHAR(1),
      VL_QUANTIDADE INT(4),
      TP_METRICA_QUANTIDADE VARCHAR(1),
      QT_MEDIA_PERMANENCIA INT(4),
      QT_PONTOS INT(4),
      VL_IDADE_MINIMA INT(4),
      TP_METRICA_IDADE_MIN VARCHAR(1),
      VL_IDADE_MAXIMA INT(4),
      TP_METRICA_IDADE_MAX VARCHAR(1),
      VL_SH INT(8),
      VL_SA INT(8),
      VL_SP INT(8),
      CO_TIPO_FINANCIAMENTO VARCHAR(2),
      CO_SUB_TIPO_FINANCIAMENTO VARCHAR(2),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8)
    );

    ALTER TABLE TB_COMPOSICAO_PROCEDIMENTO ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
    

    
    CREATE TABLE TB_FINANCIAMENTO (
      CO_FINANCIAMENTO VARCHAR(2),
      NO_FINANCIAMENTO VARCHAR(100),
      DS_FINANCIAMENTO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );



    
    CREATE TABLE TB_TIPO_FINANCIAMENTO (
      CO_TIPO_FINANCIAMENTO VARCHAR(2) PRIMARY KEY,
      NO_TIPO_FINANCIAMENTO VARCHAR(100),
      DS_TIPO_FINANCIAMENTO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
                
    ALTER TABLE TB_COMPOSICAO_PROCEDIMENTO ADD FOREIGN KEY (CO_TIPO_FINANCIAMENTO) REFERENCES TB_TIPO_FINANCIAMENTO (CO_TIPO_FINANCIAMENTO);

    CREATE TABLE TB_SUBTIPO_FINANCIAMENTO (
      CO_SUB_TIPO_FINANCIAMENTO VARCHAR(2) PRIMARY KEY,
      CO_TIPO_FINANCIAMENTO VARCHAR(2),
      NO_SUB_TIPO_FINANCIAMENTO VARCHAR(100),
      DS_SUB_TIPO_FINANCIAMENTO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    ALTER TABLE TB_COMPOSICAO_PROCEDIMENTO ADD FOREIGN KEY (CO_SUB_TIPO_FINANCIAMENTO) REFERENCES TB_SUBTIPO_FINANCIAMENTO (CO_SUB_TIPO_FINANCIAMENTO);

    ALTER TABLE TB_SUBTIPO_FINANCIAMENTO ADD FOREIGN KEY (CO_TIPO_FINANCIAMENTO) REFERENCES TB_TIPO_FINANCIAMENTO (CO_TIPO_FINANCIAMENTO);
    
    CREATE TABLE TB_ATRIBUTO_COMPLEMENTAR (
      CO_ATRIBUTO_COMPLEMENTAR VARCHAR(4) PRIMARY KEY,
      NO_ATRIBUTO_COMPLEMENTAR VARCHAR(100),
      DS_ATRIBUTO_COMPLEMENTAR VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE RL_COMPOSICAO_ATRIBUTO_COMPLEMENTAR (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_ATRIBUTO_COMPLEMENTAR VARCHAR(4),
      DT_COMPETENCIA VARCHAR(6)
    );

    ALTER TABLE RL_COMPOSICAO_ATRIBUTO_COMPLEMENTAR ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
    
    
    ALTER TABLE RL_COMPOSICAO_ATRIBUTO_COMPLEMENTAR ADD FOREIGN KEY (CO_ATRIBUTO_COMPLEMENTAR) REFERENCES TB_ATRIBUTO_COMPLEMENTAR (CO_ATRIBUTO_COMPLEMENTAR);
    
    
    
    CREATE TABLE TB_CID (
      CO_CID VARCHAR(4) PRIMARY KEY,
      NO_CID VARCHAR(100),
      ST_AGRAVO_NOTIFICACAO VARCHAR(1),
      CO_SEXO VARCHAR(1),
      ST_ESTADIO VARCHAR(1),
      CO_IRRADIADOS INT(3),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
 
    
    CREATE TABLE RL_COMPOSICAO_CID (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_CID VARCHAR(4),
      ST_PRINCIPAL VARCHAR(1),
      DT_COMPETENCIA VARCHAR(6)
    );


      
    ALTER TABLE RL_COMPOSICAO_CID ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
    
    
    ALTER TABLE RL_COMPOSICAO_CID ADD FOREIGN KEY (CO_CID) REFERENCES TB_CID (CO_CID);
    
    
    CREATE TABLE TB_CIAP2 (
      CO_CIAP2 VARCHAR(3) PRIMARY KEY,
      NO_ORIGINAL_CIAP2 VARCHAR(100),
      NO_LEI_CIAP2 VARCHAR(100),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_GRUPO_ATIVIDADE (
      CO_GRUPO_ATIVIDADE VARCHAR(2) PRIMARY KEY,
      NO_GRUPO_ATIVIDADE VARCHAR(200),
      DS_GRUPO_ATIVIDADE VARCHAR(700),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_ATIVIDADE (
      CO_GRUPO_ATIVIDADE VARCHAR(2) PRIMARY KEY,
      CO_ATIVIDADE VARCHAR(2),
      NO_ATIVIDADE VARCHAR(200),
      DS_ATIVIDADE VARCHAR(700),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    ALTER TABLE TB_ATIVIDADE ADD FOREIGN KEY (CO_GRUPO_ATIVIDADE) REFERENCES TB_GRUPO_ATIVIDADE (CO_GRUPO_ATIVIDADE);

    CREATE TABLE TB_TIPO_MARCACAO (
      CO_TIPO_MARCACAO VARCHAR(2) PRIMARY KEY ,
      NO_TIPO_MARCACAO VARCHAR(200),
      DS_TIPO_MARCACAO VARCHAR(700),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_AREA_TEMATICA (
      CO_AREA_TEMATICA VARCHAR(2) PRIMARY KEY,
      NO_AREA_TEMATICA VARCHAR(200),
      DS_AREA_TEMATICA VARCHAR(700),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_MARCACAO_FEDERAL (
      CO_AREA_TEMATICA VARCHAR(2),
      CO_MARCACAO_FEDERAL VARCHAR(2) PRIMARY KEY,
      NO_MARCACAO_FEDERAL VARCHAR(200),
      DS_MARCACAO_FEDERAL VARCHAR(700),
      CO_TIPO_MARCACAO VARCHAR(2),
      TP_SITUACAO VARCHAR(1),
      FL_LEITO VARCHAR(1),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    ALTER TABLE TB_MARCACAO_FEDERAL ADD FOREIGN KEY (CO_AREA_TEMATICA) REFERENCES TB_AREA_TEMATICA (CO_AREA_TEMATICA);
      
    ALTER TABLE TB_MARCACAO_FEDERAL ADD FOREIGN KEY (CO_TIPO_MARCACAO) REFERENCES TB_TIPO_MARCACAO (CO_TIPO_MARCACAO);
    
    CREATE TABLE TB_GRUPO_HABILITACAO (
      CO_GRUPO_HABILITACAO VARCHAR(2) PRIMARY KEY,
      NO_GRUPO_HABILITACAO VARCHAR(100),
      DS_GRUPO_HABILITACAO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (
      CO_GRUPO_HABILITACAO VARCHAR(2),
      CO_MARCACAO_FEDERAL VARCHAR(4),
      DT_COMPETENCIA VARCHAR(6)
    );

        
    ALTER TABLE RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL ADD FOREIGN KEY (CO_GRUPO_HABILITACAO) REFERENCES TB_GRUPO_HABILITACAO (CO_GRUPO_HABILITACAO);
      
    ALTER TABLE RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL ADD FOREIGN KEY (CO_MARCACAO_FEDERAL) REFERENCES TB_MARCACAO_FEDERAL (CO_MARCACAO_FEDERAL);
    
    
    CREATE TABLE RL_COMPOSICAO_MARCACAO_FEDERAL (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_MARCACAO_FEDERAL VARCHAR(4),
      DT_COMPETENCIA VARCHAR(6)
    );

        
    ALTER TABLE RL_COMPOSICAO_MARCACAO_FEDERAL ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
    
    ALTER TABLE RL_COMPOSICAO_MARCACAO_FEDERAL ADD FOREIGN KEY (CO_MARCACAO_FEDERAL) REFERENCES TB_MARCACAO_FEDERAL (CO_MARCACAO_FEDERAL);
    
    
    CREATE TABLE RL_COMPOSICAO_INCREMENTO (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_MARCACAO_FEDERAL VARCHAR(4),
      VL_PERCENTUAL_SH INT(8),
      VL_PERCENTUAL_SA INT(8),
      VL_PERCENTUAL_SP INT(8),
      DT_COMPETENCIA VARCHAR(6)
    );

    ALTER TABLE RL_COMPOSICAO_INCREMENTO ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
    
    ALTER TABLE RL_COMPOSICAO_INCREMENTO ADD FOREIGN KEY (CO_MARCACAO_FEDERAL) REFERENCES TB_MARCACAO_FEDERAL (CO_MARCACAO_FEDERAL);
    
    CREATE TABLE TB_LEITO (
      CO_LEITO VARCHAR(2) PRIMARY KEY,
      NO_LEITO VARCHAR(100),
      DS_LEITO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE RL_COMPOSICAO_LEITO (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_LEITO VARCHAR(2),
      DT_COMPETENCIA VARCHAR(6)
    );
    
        
    ALTER TABLE RL_COMPOSICAO_LEITO ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
     
    ALTER TABLE RL_COMPOSICAO_LEITO ADD FOREIGN KEY (CO_LEITO) REFERENCES TB_LEITO (CO_LEITO);
    
    
    CREATE TABLE TB_MODALIDADE_ASSISTENCIAL (
      CO_MODALIDADE_ASSISTENCIAL VARCHAR(2),
      NO_MODALIDADE_ASSISTENCIAL VARCHAR(100),
      DS_MODALIDADE_ASSISTENCIAL VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_SEXO (
      CO_SEXO VARCHAR(1) PRIMARY KEY,
      NO_SEXO VARCHAR(20),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );

    ALTER TABLE TB_CID ADD FOREIGN KEY (CO_SEXO) REFERENCES TB_SEXO (CO_SEXO); 

    
    CREATE TABLE TB_PAIS (
      CO_PAIS VARCHAR(3),
      NO_PAIS VARCHAR(150),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_MUNICIPIO (
      CO_MUNICIPIO_IBGE VARCHAR(6),
      NO_MUNICIPIO VARCHAR(255),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE RL_COMPOSICAO_SEXO (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_SEXO VARCHAR(1),
      DT_COMPETENCIA VARCHAR(6)
    );

    ALTER TABLE RL_COMPOSICAO_SEXO ADD FOREIGN KEY (CO_SEXO) REFERENCES TB_SEXO (CO_SEXO);
        
    ALTER TABLE RL_COMPOSICAO_SEXO ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);

    
    
    CREATE TABLE TB_SERVICO (
      CO_SERVICO VARCHAR(3) PRIMARY KEY,
      NO_SERVICO VARCHAR(100),
      DS_SERVICO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_CLASSIFICACAO (
      CO_SERVICO VARCHAR(3),
      CO_CLASSIFICACAO VARCHAR(3) PRIMARY KEY,
      NO_CLASSIFICACAO VARCHAR(100),
      DS_CLASSIFICACAO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
       
    ALTER TABLE TB_CLASSIFICACAO ADD FOREIGN KEY (CO_SERVICO) REFERENCES TB_SERVICO (CO_SERVICO);

    CREATE TABLE RL_COMPOSICAO_CLASSIFICACAO (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_SERVICO VARCHAR(3),
      CO_CLASSIFICACAO VARCHAR(3),
      DT_COMPETENCIA VARCHAR(6)
    );
    
     
    ALTER TABLE RL_COMPOSICAO_CLASSIFICACAO ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
    
    ALTER TABLE RL_COMPOSICAO_CLASSIFICACAO ADD FOREIGN KEY (CO_SERVICO) REFERENCES TB_SERVICO (CO_SERVICO);
    
    ALTER TABLE RL_COMPOSICAO_CLASSIFICACAO ADD FOREIGN KEY (CO_CLASSIFICACAO) REFERENCES TB_CLASSIFICACAO (CO_CLASSIFICACAO);
    
    CREATE TABLE TB_CBO (
      CO_CBO VARCHAR(6) PRIMARY KEY,
      NO_CBO VARCHAR(100),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE RL_COMPOSICAO_CBO (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_CBO VARCHAR(6),
      DT_COMPETENCIA VARCHAR(6)
    );

    
    ALTER TABLE RL_COMPOSICAO_CBO ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
       
    ALTER TABLE RL_COMPOSICAO_CBO ADD FOREIGN KEY (CO_CBO) REFERENCES TB_CBO (CO_CBO);
    
    
    CREATE TABLE TB_FAMILIA_CBO (
      CO_FAMILIA_CBO VARCHAR(4) PRIMARY KEY,
      NO_FAMILIA_CBO VARCHAR(100),
      DS_FAMILIA_CBO VARCHAR(500),
      ST_ASSOCIAVEL_PROCEDIMENTO VARCHAR(1),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE RL_COMPOSICAO_FAMILIA_CBO (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_FAMILIA_CBO VARCHAR(4),
      DT_COMPETENCIA VARCHAR(6)
    );

        
    ALTER TABLE RL_COMPOSICAO_FAMILIA_CBO ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
      
    ALTER TABLE RL_COMPOSICAO_FAMILIA_CBO ADD FOREIGN KEY (CO_FAMILIA_CBO) REFERENCES TB_FAMILIA_CBO (CO_FAMILIA_CBO);
    
    
    CREATE TABLE RL_COMPOSICAO_PROCEDIMENTO_ORIGEM (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_PROCEDIMENTO_ORIGEM VARCHAR(10),
      DT_COMPETENCIA VARCHAR(6)
    );
       
    ALTER TABLE RL_COMPOSICAO_PROCEDIMENTO_ORIGEM ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
    
    
    CREATE TABLE TB_CARATER_ATENDIMENTO (
      CO_CARATER_ATENDIMENTO VARCHAR(2),
      NO_CARATER_ATENDIMENTO VARCHAR(100),
      DS_CARATER_ATENDIMENTO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_CBHPM (
      CO_CBHPM VARCHAR(8),
      NO_CBHPM VARCHAR(100),
      DS_CBHPM VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_TUSS (
      CO_TUSS VARCHAR(8) PRIMARY KEY,
      NO_TUSS VARCHAR(100),
      DS_TUSS VARCHAR(1000),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE RL_COMPOSICAO_TUSS (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_TUSS VARCHAR(8),
      DT_COMPETENCIA VARCHAR(6)
    );
        
    ALTER TABLE RL_COMPOSICAO_TUSS ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
    
    ALTER TABLE RL_COMPOSICAO_TUSS ADD FOREIGN KEY (CO_TUSS) REFERENCES TB_TUSS (CO_TUSS);
    
    
    CREATE TABLE TB_REGRA_REGISTRO (
      CO_REGRA_REGISTRO VARCHAR(4) PRIMARY KEY,
      NO_REGRA_REGISTRO VARCHAR(100),
      DS_REGRA_REGISTRO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE RL_COMPOSICAO_REGRA_REGISTRO (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_REGRA_REGISTRO VARCHAR(4),
      DT_COMPETENCIA VARCHAR(6)
    );

        
    ALTER TABLE RL_COMPOSICAO_REGRA_REGISTRO ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO); 
    
    ALTER TABLE RL_COMPOSICAO_REGRA_REGISTRO ADD FOREIGN KEY (CO_REGRA_REGISTRO) REFERENCES TB_REGRA_REGISTRO (CO_REGRA_REGISTRO);
    
    
    CREATE TABLE TB_DESFECHO (
      CO_DESFECHO VARCHAR(2),
      NO_DESFECHO VARCHAR(100),
      DS_DESFECHO VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_ETNIA (
      CO_ETNIA VARCHAR(3),
      CO_RACA_COR VARCHAR(2),
      NO_ETNIA VARCHAR(100),
      DS_ETNIA VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_JUSTIFICATIVA_IMPOSSIBILIDADE_IDENTIFICACAO_INDIVIDUO (
      CO_JUSTIFICATIVA_CNS VARCHAR(2),
      NO_JUSTIFICATIVA_CNS VARCHAR(100),
      DS_JUSTIFICATIVA_CNS VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_PROCEDENCIA (
      CO_PROCEDENCIA VARCHAR(2),
      NO_PROCEDENCIA VARCHAR(100),
      DS_PROCEDENCIA VARCHAR(500),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_RACA_COR (
      CO_RACA_COR VARCHAR(2),
      NO_RACA_COR VARCHAR(50),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_RENASES (
      CO_RENASES VARCHAR(3) PRIMARY KEY,
      NO_RENASES VARCHAR(200),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE RL_COMPOSICAO_RENASES (
      CO_PROCEDIMENTO VARCHAR(10),
      CO_RENASES VARCHAR(3),
      DT_COMPETENCIA VARCHAR(6)
    );

    ALTER TABLE RL_COMPOSICAO_RENASES ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
    
    ALTER TABLE RL_COMPOSICAO_RENASES ADD FOREIGN KEY (CO_RENASES) REFERENCES TB_RENASES (CO_RENASES);
    
    
    CREATE TABLE TB_CBARA_TIPO (
      CO_TIPO VARCHAR(50),
      NO_TIPO VARCHAR(200),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_REACAO_ADVERSA (
      CO_REACAO_ADVERSA VARCHAR(50),
      NO_REACAO_ADVERSA VARCHAR(200),
      DS_REACAO_ADVERSA VARCHAR(500),
      DS_SINONIMO_1 VARCHAR(200),
      DS_SINONIMO_2 VARCHAR(200),
      CO_MEDDRA VARCHAR(8),
      DS_MEDDRA VARCHAR(200),
      CO_CID10 VARCHAR(4),
      CO_CIAP2 VARCHAR(3),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );

        
    ALTER TABLE TB_REACAO_ADVERSA ADD FOREIGN KEY (CO_CIAP2) REFERENCES TB_CIAP2 (CO_CIAP2);
    
    
    CREATE TABLE TB_CBARA_CATERIA (
      CO_CATERIA VARCHAR(50) PRIMARY KEY,
      NO_CATERIA VARCHAR(200),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_CBARA_AGENTE (
      CO_AGENTE VARCHAR(50),
      NO_AGENTE VARCHAR(200),
      DS_SINONIMO_1 VARCHAR(200),
      DS_SINONIMO_2 VARCHAR(200),
      CO_CATERIA VARCHAR(50),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
      
    ALTER TABLE TB_CBARA_AGENTE ADD FOREIGN KEY (CO_CATERIA) REFERENCES TB_CBARA_CATERIA (CO_CATERIA);
    
    CREATE TABLE TB_LOINC (
      CO_LOINC VARCHAR(10),
      NO_ORIGINAL_INGLES VARCHAR(255),
      NO_ORIGINAL VARCHAR(400),
      NO_CURTO_INGLES VARCHAR(255),
      NO_CURTO VARCHAR(200),
      CO_PROPRIEDADES_INGLES VARCHAR(40),
      CO_PROPRIEDADES VARCHAR(40),
      CO_COMPONENTE_INGLES VARCHAR(150),
      CO_COMPONENTE VARCHAR(150),
      CO_TEMPO_INGLES VARCHAR(40),
      CO_TEMPO VARCHAR(40),
      CO_SISTEMAS_INGLES VARCHAR(40),
      CO_SISTEMAS VARCHAR(40),
      CO_ESCALA_INGLES VARCHAR(40),
      CO_ESCALA VARCHAR(40),
      CO_METODO_INGLES VARCHAR(150),
      CO_METODO VARCHAR(150),
      CO_CLASSES_INGLES VARCHAR(40),
      CO_CLASSES VARCHAR(40),
      CO_PROCEDIMENTO VARCHAR(10),
      CO_TUSS VARCHAR(9),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );

        
    ALTER TABLE TB_LOINC ADD FOREIGN KEY (CO_PROCEDIMENTO) REFERENCES TB_PROCEDIMENTO (CO_PROCEDIMENTO);
      
    ALTER TABLE TB_LOINC ADD FOREIGN KEY (CO_TUSS) REFERENCES TB_TUSS (CO_TUSS);
    
    
    CREATE TABLE TB_LOINC_CLASSES (
      DS_ABREVIATURA_INGLES VARCHAR(40),
      DS_ABREVIATURA VARCHAR(40),
      NO_CLASSES_INGLES VARCHAR(255),
      NO_CLASSES VARCHAR(400),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_LOINC_COMPONENTE (
      DS_ABREVIATURA_INGLES VARCHAR(150),
      DS_ABREVIATURA VARCHAR(150),
      NO_COMPONENTE_INGLES VARCHAR(255),
      NO_COMPONENTE VARCHAR(400),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_LOINC_PROPRIEDADES (
      DS_ABREVIATURA_INGLES VARCHAR(40),
      DS_ABREVIATURA VARCHAR(40),
      NO_PROPRIEDADES_INGLES VARCHAR(255),
      NO_PROPRIEDADES VARCHAR(400),
      DS_TIPO_INGLES VARCHAR(255),
      DS_TIPO VARCHAR(400),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_LOINC_SISTEMAS (
      DS_ABREVIATURA_INGLES VARCHAR(40),
      DS_ABREVIATURA VARCHAR(40),
      NO_SISTEMAS_INGLES VARCHAR(255),
      NO_SISTEMAS VARCHAR(400),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_LOINC_TEMPO (
      DS_ABREVIATURA_INGLES VARCHAR(40),
      DS_ABREVIATURA VARCHAR(40),
      NO_TEMPO_INGLES VARCHAR(255),
      NO_TEMPO VARCHAR(400),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_LOINC_TP_ESCALA (
      DS_ABREVIATURA_INGLES VARCHAR(40),
      DS_ABREVIATURA VARCHAR(40),
      NO_ESCALA_INGLES VARCHAR(255),
      NO_ESCALA VARCHAR(400),
      DS_TP_ESCALA_INGLES VARCHAR(255),
      DS_TP_ESCALA VARCHAR(400),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );
    
    
    CREATE TABLE TB_LOINC_TP_METODO (
      DS_ABREVIATURA_INGLES VARCHAR(150),
      DS_ABREVIATURA VARCHAR(150),
      NO_METODO_INGLES VARCHAR(255),
      NO_METODO VARCHAR(400),
      DT_COMPETENCIA VARCHAR(6),
      CO_VERSAO VARCHAR(8),
      ST_ACAO INT(1)
    );

    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        DROP TABLE IF EXISTS "TB_GRUPO"
        DROP TABLE "TB_GRUPO";
        DROP TABLE "TB_SUBGRUPO";
        DROP TABLE "TB_FORMA_ORGANIZACAO";
        DROP TABLE "TB_PROCEDIMENTO";
        DROP TABLE "TB_COMPOSICAO_PROCEDIMENTO";
        DROP TABLE "TB_FINANCIAMENTO";
        DROP TABLE "TB_TIPO_FINANCIAMENTO";
        DROP TABLE "TB_SUBTIPO_FINANCIAMENTO";
        DROP TABLE "TB_ATRIBUTO_COMPLEMENTAR";
        DROP TABLE "RL_COMPOSICAO_ATRIBUTO_COMPLEMENTAR";
        DROP TABLE "TB_CID";
        DROP TABLE "RL_COMPOSICAO_CID";
        DROP TABLE "TB_CIAP2";
        DROP TABLE "TB_GRUPO_ATIVIDADE";
        DROP TABLE "TB_ATIVIDADE";
        DROP TABLE "TB_TIPO_MARCACAO";
        DROP TABLE "TB_AREA_TEMATICA";
        DROP TABLE "TB_MARCACAO_FEDERAL";
        DROP TABLE "TB_GRUPO_HABILITACAO";
        DROP TABLE "RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL";
        DROP TABLE "RL_COMPOSICAO_MARCACAO_FEDERAL";
        DROP TABLE "RL_COMPOSICAO_INCREMENTO";
        DROP TABLE "TB_LEITO";
        DROP TABLE "RL_COMPOSICAO_LEITO";
        DROP TABLE "TB_MODALIDADE_ASSISTENCIAL";
        DROP TABLE "TB_SEXO";
        DROP TABLE "TB_PAIS";
        DROP TABLE "TB_MUNICIPIO";
        DROP TABLE "RL_COMPOSICAO_SEXO";
        DROP TABLE "TB_SERVICO";
        DROP TABLE "TB_CLASSIFICACAO";
        DROP TABLE "RL_COMPOSICAO_CLASSIFICACAO";
        DROP TABLE "TB_CBO";
        DROP TABLE "RL_COMPOSICAO_CBO";
        DROP TABLE "TB_FAMILIA_CBO";
        DROP TABLE "RL_COMPOSICAO_FAMILIA_CBO";
        DROP TABLE "RL_COMPOSICAO_PROCEDIMENTO_ORIGEM";
        DROP TABLE "TB_CARATER_ATENDIMENTO";
        DROP TABLE "TB_CBHPM";
        DROP TABLE "TB_TUSS";
        DROP TABLE "RL_COMPOSICAO_TUSS";
        DROP TABLE "TB_REGRA_REGISTRO";
        DROP TABLE "RL_COMPOSICAO_REGRA_REGISTRO";
        DROP TABLE "TB_DESFECHO";
        DROP TABLE "TB_ETNIA";
        DROP TABLE "TB_JUSTIFICATIVA_IMPOSSIBILIDADE_IDENTIFICACAO_INDIVIDUO";
        DROP TABLE "TB_PROCEDENCIA";
        DROP TABLE "TB_RACA_COR";
        DROP TABLE "TB_RENASES";
        DROP TABLE "RL_COMPOSICAO_RENASES";
        DROP TABLE "TB_CBARA_TIPO";
        DROP TABLE "TB_REACAO_ADVERSA";
        DROP TABLE "TB_CBARA_CATERIA";
        DROP TABLE "TB_CBARA_AGENTE";
        DROP TABLE "TB_LOINC";
        DROP TABLE "TB_LOINC_CLASSES";
        DROP TABLE "TB_LOINC_COMPONENTE";
        DROP TABLE "TB_LOINC_PROPRIEDADES";
        DROP TABLE "TB_LOINC_SISTEMAS";
        DROP TABLE "TB_LOINC_TEMPO";
        DROP TABLE "TB_LOINC_TP_ESCALA";
        DROP TABLE "TB_LOINC_TP_METODO";
    `);
  }
}
