import { MigrationInterface, QueryRunner } from 'typeorm';

export class TB_LOINC_SISTEMASMigration1694458279819
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO ) VALUES ('Bld.dot', 'Amostra de sangue seco (DBS)', 'Blood filter paper', 'Sangue em papel de filtro', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Isol./Spec.', 'Isolada Amostra', 'Isolate/Specimen', 'Isolada/Amostra', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Isolate', 'Isolado', 'Isolate', 'Isolado', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Nose', 'Nariz', 'Nose (nasal passage)', 'Nariz (passagem nasal)', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Nph', 'Nasofaringe', 'Naspopharynx', 'Nasofaringe', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Oropharyngeal wash', 'Lavagem orofaríngea (gagarejo)', 'Oropharyngeal wash', 'Lavagem orofaríngea (gagarejo)', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Respiratory', 'Respiratório', 'Respiratory System', 'Sistema Respiratório', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Respiratory.lower', 'Respiratório inferior', 'Lower Respiratory system', 'Sistema Respiratório Inferior', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Respiratory.upper', 'Respiratório superior', 'Upper Respiratóry System', 'sistema Respiratório Superior', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Saliva', 'Saliva', 'Saliva', 'Saliva', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Ser', 'Soro', 'Serum', 'Soro', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Ser/Plas', 'Soro Plasma', 'Serum/Plasma', 'Soro/plasma', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Ser/Plas/Bld', 'Soro Plasma Sangue', 'Serum/Plasma/whole blood', 'Soro/plasma/sangue total', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('Spec.', 'Amostra', 'Specimen', 'Amostra', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('XXX', 'XXX', 'XXX', 'Inespecífico', '202308', '08/2021A', '2');
INSERT INTO TB_LOINC_SISTEMAS (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_SISTEMAS_INGLES,NO_SISTEMAS,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('XXX^Donor', 'XXX^Doador', 'XXX^Donor', 'XXX^Doador', '202308', '08/2021A', '2');

`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverta a migração se necessário
  }
}
