import { MigrationInterface, QueryRunner } from 'typeorm';

export class TB_SUBGRUPOMigration1694458279978 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO ) VALUES ('01', '02', 'Vigilância em saúde', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '01', 'Coleta de material', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '02', 'Diagnóstico em laboratório clínico', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '03', 'Diagnóstico por anatomia patológica e citopatologia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '04', 'Diagnóstico por radiologia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '05', 'Diagnóstico por ultrasonografia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '06', 'Diagnóstico por tomografia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '07', 'Diagnóstico por ressonância magnética', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '08', 'Diagnóstico por medicina nuclear in vivo', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '09', 'Diagnóstico por endoscopia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '10', 'Diagnóstico por radiologia intervencionista', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '11', 'Métodos diagnósticos em especialidades', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '12', 'Diagnóstico e procedimentos especiais em hemoterapia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '13', 'Diagnóstico em vigilância epidemiológica e ambiental', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '14', 'Diagnóstico por teste rápido', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '01', 'Consultas / Atendimentos / Acompanhamentos', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '02', 'Fisioterapia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '03', 'Tratamentos clínicos (outras especialidades)', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '04', 'Tratamento em oncologia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '05', 'Tratamento em nefrologia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '06', 'Hemoterapia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '07', 'Tratamentos odontológicos', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '08', 'Tratamento de lesões, envenenamentos e outros, decorrentes de causas externas', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '09', 'Terapias especializadas', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '10', 'Parto e nascimento', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '01', 'Pequenas cirurgias e cirurgias de pele, tecido subcutâneo e mucosa', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '02', 'Cirurgia de glândulas endócrinas', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '03', 'Cirurgia do sistema nervoso central e periférico', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '04', 'Cirurgia das vias aéreas superiores, da face, da cabeça e do pescoço', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '05', 'Cirurgia do aparelho da visão', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '06', 'Cirurgia do aparelho circulatório', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '07', 'Cirurgia do aparelho digestivo, orgãos anexos e parede abdominal', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '08', 'Cirurgia do sistema osteomuscular', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '09', 'Cirurgia do aparelho geniturinário', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '10', 'Cirurgia de mama', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '11', 'Cirurgia obstétrica', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '12', 'Cirurgia torácica', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '13', 'Cirurgia reparadora', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '14', 'Bucomaxilofacial', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '15', 'Outras cirurgias', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '16', 'Cirurgia em oncologia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '17', 'Anestesiologia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '18', 'Cirurgia em nefrologia', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('05', '01', 'Coleta e exames para fins de doação de orgãos, tecidos e células e de transplante', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('05', '02', 'Avaliação de morte encefálica', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('05', '03', 'Ações relacionadas à doação de orgãos e tecidos para transplante', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('05', '04', 'Processamento de tecidos para transplante', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('05', '05', 'Transplante de orgãos, tecidos e células', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('05', '06', 'Acompanhamento e intercorrências no pré e pós-transplante', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('06', '01', 'Medicamentos de dispensação excepcional', '202308', '02/2017B', '7');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('06', '02', 'Medicamentos estratégicos', '202308', '03/2018A', '7');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('06', '03', 'Medicamentos de âmbito hospitalar e urgência', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('06', '04', 'Componente Especializado da Assitencia Farmaceutica', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('07', '01', 'Órteses, próteses e materiais especiais não relacionados ao ato cirúrgico', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('07', '02', 'Órteses, próteses e materiais especiais relacionados ao ato cirúrgico', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('08', '01', 'Ações relacionadas ao estabelecimento', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('08', '02', 'Ações relacionadas ao atendimento', '202308', '01/2017A', '2');
INSERT INTO TB_SUBGRUPO (CO_GRUPO, CO_SUB_GRUPO, NO_SUB_GRUPO, DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('08', '03', 'Autorização / Regulação', '202308', '01/2017A', '2');

`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverta a migração se necessário
  }
}
