import { MigrationInterface, QueryRunner } from 'typeorm';

export class TB_SERVICOMigration1694458279970 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO ) VALUES ('101', 'Serviço de Estratégia de Saúde da Família', '202308', '08/2020A', '7');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('102', 'Serviço de Estratégias de Agentes Comunitário de Saúde', '202308', '08/2020A', '7');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('103', 'Serviço de Atendimento Móvel de Urgências', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('104', 'Serviço de Regulação do Acesso a Ações e Serviços de Saúde', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('105', 'Serviço de Atenção em Neurologia/ Neurocirurgia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('106', 'Serviço de Atenção a DST/HIV/AIDS', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('107', 'Serviço de Atenção a Saúde Auditiva', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('108', 'Serviço de Atenção a Saúde do Trabalhador', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('109', 'Serviço de Atenção a Saúde dos Adolescentes em conflito com a Lei, em regime internação/int. provis.', '202308', '08/2020A', '7');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('110', 'Serviço de Atenção a Saúde Reprodutiva', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('111', 'Serviço de Atenção ao Paciente com Tuberculose', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('112', 'Atenção ao Pré-Natal e Nascimento', '202308', '08/2022B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('113', 'Serviço de Atenção Domiciliar', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('114', 'Serviço de Atenção em Saúde Bucal', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('115', 'Atenção Psicossocial', '202308', '09/2022A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('116', 'Serviço de Atenção Cardiovascular/Cardiologia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('117', 'Serviço de Cirurgia Reparadora', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('118', 'Serviço de Cirurgia Torácica', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('119', 'Serviço de Controle de Tabagismo', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('120', 'Serviço de Diagnóstico por Anatomia Patológica e/ou Citopatologia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('121', 'Serviço de Diagnóstico por Imagem', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('122', 'Serviço de Diagnóstico por Métodos Gráficos/Dinâmicos', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('123', 'Serviço de Dispensação de Órteses, Próteses e Materiais Especiais', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('124', 'Serviço de Endocrinologia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('125', 'Serviço de Farmácia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('126', 'Serviço de Fisioterapia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('127', 'Serviço de Atenção à Obesidade', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('128', 'Serviço de Hemoterapia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('129', 'Servico de Laboratório de Histocompatibilidade', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('130', 'Serviço de Atenção à Doença Renal Crônica', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('131', 'Serviço de Oftalmologia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('132', 'Serviço de Oncologia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('133', 'Serviço de Pneumologia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('134', 'Serviço de Práticas Integrativas e Complementares', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('135', 'Serviço de Reabilitação', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('136', 'Serviço de Suporte Nutricional', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('137', 'Serviço de Telemedicina', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('138', 'Serviço de Traumato-Ortopedia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('139', 'Serviço de Triagem Neonatal', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('140', 'Serviço de Urgência e Emergência', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('141', 'Serviço de Vigilância em Saúde', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('142', 'Serviço de Endoscopia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('143', 'Serviço Móvel de Urgência (exceto SAMU)', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('144', 'Serviço Posto de Coleta de Materiais Biológicos', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('145', 'Serviço de Diagnóstico por Laboratório Clínico', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('146', 'Serviço de Videolaparoscopia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('147', 'Serviço de Apoio a Saúde da Família', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('148', 'Serviço de Hospital-Dia', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('149', 'Serviço de Transplante', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('150', 'Serviço de Cirurgia Vascular', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('151', 'Serviço de Medicina Nuclear', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('152', 'Serviço de Atenção à Saúde de Populações Indígenas', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('153', 'Serviço de Atenção Especializada no Processo Transexualizador', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('154', 'Serviço de Banco de Tecidos', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('155', 'Serviço de Traumatologia  Ortopedia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('156', 'Serviço de Atenção á Saúde das Pessoas Ostomizadas', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('157', 'Serviço de Laboratório de Prótese Dentária', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('158', 'Serviço de Atenção Integral em Hanseniase', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('159', 'Serviço de Atenção Primária', 'realiza um conjunto de ações de saúde, no âmbito individual e coletivo, que abrange a promoção e a proteção da saúde, a prevenção de agravos, o diagnóstico, o tratamento, a reabilitação, a redução de danos e a manutenção da saúde', '202308', '06/2020C', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('160', 'Serviço de Teleconsultoria', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('161', 'Serviço de Consultório na Rua', '202308', '08/2020A', '7');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('162', 'Serviço de Terapia Intensiva', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('163', 'Serviço de Cuidados Intermediários', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('164', 'Serviço de Órteses,Próteses e Materiais Especiais em Reabilitação', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('165', 'Serviço de Atenção às Pessoas em Situação de Violência Sexual', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('166', 'Serviço de Análise Laboratorial de Produtos Sujeitos a Vigilância Sanitária', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('167', 'Serviço de Atendimento Itinerante de Assistência e Ensino em Saúde', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('168', 'Serviço de Atenção às Pessoas com Doenças Raras', '202308', '01/2017B', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('169', 'Serviço de Atenção em Urologia', '202308', '01/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('170', 'Serviço de Comissões e Comitês', '202308', '08/2017A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('173', 'Serviço de Logística de Imunobiológicos', '202308', '04/2019A', '2');
INSERT INTO TB_SERVICO (CO_SERVICO, NO_SERVICO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('174', 'Serviço de Imunização', '202308', '04/2019A', '2');

`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverta a migração se necessário
  }
}
