import { MigrationInterface, QueryRunner } from 'typeorm';

export class TB_AREA_TEMATICAMigration1694458279493
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', 'Atenção a Obesidade Grave', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', 'Atenção a Saúde Auditiva', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', 'Atenção a Saúde Bucal', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('05', 'Atenção a Saúde Ocular', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('06', 'Atenção a Saúde Mental', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('07', 'Atenção a Saúde do Trabalhador', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('08', 'Cardiovascular', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('09', 'Cuidados Prolongados', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('10', 'Dor Crônica', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('11', 'DST/Aids', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('12', 'Hospital Dia', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('13', 'Internação domiciliar', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('14', 'Materno-Infantil', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('15', 'Nefrologia', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('16', 'Neurologia/Neurocirurgia', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('17', 'Oncologia', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('18', 'Osteogênesis Imperfecta', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('19', 'Planejamento Familiar / Esterilização', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('20', 'Pneumologia', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('21', 'Queimados', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('22', 'Reabilitação', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('23', 'Terapia Nutricional', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('24', 'Transplantes', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('25', 'Traumato-ortopedia', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('26', 'Unidade Terapia Intensiva', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('27', 'Urgência', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('28', 'Unidade de Cuidados Intermediários Neonatal', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('29', 'Videocirurgias', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('30', 'Transexualizador', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('31', 'Hospitais Contratos de Gestão', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('32', 'Saúde da Mulher', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('34', 'Atenção ao Trauma', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('35', 'Atenção às Pessoas com Doenças Raras', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('36', 'Sangue e Hemoderivado', '202308', '01/2017A', '2');
INSERT INTO TB_AREA_TEMATICA (CO_AREA_TEMATICA,NO_AREA_TEMATICA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('37', 'Atenção às Pessoas em Situação de Violência Sexual', '202308', '01/2017A', '2');
`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverta a migração se necessário
  }
}
