import { MigrationInterface, QueryRunner } from 'typeorm';

export class RL_GRUPO_HABILITACAO_MARCACAO_FEDERALMigration1695458279490
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('01', '0801', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('02', '0801', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('02', '0804', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('03', '0802', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('03', '0807', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('04', '0806', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('04', '0802', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('05', '0805', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('05', '0802', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('06', '0802', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('06', '0804', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('07', '0802', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('07', '0803', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('08', '0801', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('08', '0807', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('09', '0806', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('09', '0801', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('10', '0801', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('10', '0805', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('11', '2301', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('11', '2303', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('12', '2304', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('12', '2301', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('13', '2305', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('13', '2301', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('14', '2303', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('14', '2302', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('15', '2304', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('15', '2302', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('16', '2302', '202308');
INSERT INTO RL_GRUPO_HABILITACAO_MARCACAO_FEDERAL (CO_GRUPO_HABILITACAO,CO_MARCACAO_FEDERAL,DT_COMPETENCIA) VALUES ('16', '2305', '202308');

`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverta a migração se necessário
  }
}
