import { MigrationInterface, QueryRunner } from 'typeorm';

export class TB_ATIVIDADEMigration1695458279519 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '01', 'Vigilância de Zoonoses', 'Conjunto de ações, serviços e estratégias relacionadas a animais de relevância para a saúde pública, devendo obrigatoriamente contemplar: a educação em saúde visando à prevenção de zoonoses; a Imunização animal contra zoonoses normatizadas pelo Ministério da Saúde; o diagnóstico laboratorial de zoonoses e identificação das espécies de animais; a coleta, recebimento, acondicionamento, conservação e transporte de espécimes ou amostras biológicas de animais para encaminhamento aos laboratórios, com vistas à identificação ou diagnóstico laboratorial de zoonoses; o gerenciamento de resíduos oriundos dos serviços gerados pelas atividades de vigilância em zoonoses; o recolhimento e transporte de...', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '01', 'Administração', 'Compreende os processos de formulação, implementação, planejamento e administração das políticas, sistemas e práticas de saúde. Abrange a organização dos serviços de saúde, bem como a articulação das práticas de saúde (individual e coletiva) nos níveis central, regional e local de um sistema ou rede de saúde. Inclui-se as atividades realizadas para a gestão, controle, avaliação e auditoria de sistemas ou redes de saúde, bem como a atividade administrativa do Tratamento Fora de Domicílio. Exclui-se as atividades de gestão interna nos estabelecimentos e serviços de saúde.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '01', 'Hospitalidade', 'Serviços que visam alojar temporariamente e apoiar indivíduos que necessitam permanecer fora de sua residência/moradia para acessar serviços de saúde não ofertados em sua localidade de origem, podendo dispor de atividades assistenciais simples, principalmente relacionados a cuidados básicos.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '02', 'Apoio Diagnóstico', 'Ações e serviços que se utilizam de recursos físicos e tecnológicos (ex: Raios X, Ultrassonografia, Ressonância Magnética, Análises Clínicas/ Laboratoriais, Eletrocardiografia, Endoscopia, etc) com o objetivo de auxiliar, de forma complementar, a determinação da natureza de uma doença ou estado, ou a diferenciação entre elas, melhorando a tomada de decisão assistencial.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '02', 'Análises Laboratoriais de Vigilância em Saúde', 'Ações e serviços de análises laboratoriais de interesse à saúde pública, relacionadas a vigilância epidemiológica, vigilância em saúde ambiental, saúde do trabalhador e vigilância sanitária, vinculado a órgãos ou entidades da Administração Pública direta ou indireta, da União, dos Estados, do Distrito Federal ou dos Municípios, e das fundações mantidas pelo poder Público', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '02', 'Regulação Assistencial', 'Compreende a organização, o controle, o gerenciamento e a priorização do acesso e dos fluxos assistenciais, por meio de autoridade sanitária exercida por profissional de saúde no seu âmbito de atuação legal, para a garantia do acesso baseada em protocolos, classificação de risco e demais critérios de priorização. Inclui-se as atividades de regulação assistencial realizadas tanto pelo Sistema Único de Saúde quanto pelas operadoras de planos de saúde, seja hospitalar ou ambulatorial, eletiva ou de urgência, as atividades de regulação de ambulâncias públicas ou privadas.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('04', '02', 'Confecção de Órteses e Próteses Dentárias', 'Serviço de fabricação e produção de órteses e próteses dentárias com o intuito de apoiar ações de assistência em saúde.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '03', 'Terapias Especiais', 'Atividades voltadas exclusivamente para a realização de hemodiálise, quimioterapia, radioterapia ou cirurgias ambulatoriais.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '03', 'Vigilância de Saúde do Trabalhador', 'Ações e serviços de vigilância em saúde, clínico-assistenciais e de suporte técnico-pedagógico, voltadas para a atenção integral à saúde do trabalhador.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '03', 'Logística de Insumos', 'Compreende o armazenamento e distribuição, sem fins comerciais, para os estabelecimentos de saúde, de medicamentos, imunobiológicos, kit de diagnóstico, produtos químicos e equipamentos de controle vetorial ou produtos para a saúde.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '04', 'Reabilitação', 'Conjunto de ações e serviços orientados a desenvolver ou ampliar a capacidade funcional e desempenho dos indivíduos, proteger a saúde e prevenir agravos, de modo a contribuir para autonomia, acesso à direitos e participação em todas as esferas da vida social.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('02', '04', 'Esclarecimento da Causa Mortis de Óbitos', 'Ações e serviços de realização de autópsia para o esclarecimento da causa mortis, com ou sem assistência médica, sem elucidação diagnóstica, em especial aqueles sob investigação epidemiológica.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('03', '04', 'Logística de Órgãos, Tecidos e Células do Corpo Humano', 'Compreende as ações para o acondicionamento, gerenciamento e distribuição dos órgãos, tecidos e células do corpo humano.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '05', 'Concessão, Manutenção e Adaptação de OPM', 'As Órteses, Próteses, Materiais Especiais e Meios de Locomoção (OPM) constituem ferramentas do processo terapêutico da reabilitação, contribuindo fundamentalmente na superação de barreiras, devendo ser prescritas de forma individualizada por profissional capacitado. A concessão de OPM deve obrigatoriamente estar atrelada à adaptação, manutenção e treino de uso da mesma.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '06', 'Atenção Domiciliar', 'Ações e serviços prestados de forma substitutiva ou complementar à internação hospitalar ou atendimento ambulatorial, caracterizados pelo conjunto de tratamento de doenças, reabilitação, promoção à saúde e prevenção, englobando internação e/ou assistência prestadas em domicílio.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '07', 'Assistência a Emergências', 'Cuidados destinados a pacientes de demanda espontânea com agravos que necessitam de atendimento imediato por risco iminente de morte.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '08', 'Entrega/Dispensação de Medicamentos', 'Conjunto de ações relativas ao fornecimento de medicamentos diretamente ao paciente e a orientação para o seu uso racional, mediante apresentação de prescrição por profissional habilitado', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '09', 'Internação', 'Cuidados ou tratamentos prestados a um indivíduo, por razões clínicas e/ou cirúrgicas, que demandem a ocupação de um leito por um período igual ou superior a 24 horas', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '10', 'Assistência Intermediária', 'Conjunto de ações realizadas entre a internação e o atendimento ambulatorial, para realização de procedimentos clínicos, cirúrgicos, diagnósticos e terapêuticos, que requeiram a permanência do paciente em um leito por um período inferior a 24 horas.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '11', 'Atenção Psicossocial', 'Conjunto de ações intersetoriais de caráter territorial e comunitário que visa à substituição do modelo asilar manicomial, por meio de cuidados que possibilitem a reabilitação psicossocial das pessoas em sofrimento psíquico ou transtorno mental, incluindo aquelas com necessidades decorrentes do uso de álcool e outras drogas, garantindo atenção contínua às situações de crise em saúde mental e articulação do cuidado com outros pontos de atenção', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '12', 'Atenção Básica', 'Conjunto de ações e serviços longitudinais de saúde no âmbito individual e coletivo, de caráter territorial e comunitário, que abrange o cuidado/tratamento, a promoção e proteção da saúde, a prevenção de agravos, a vigilância em saúde, a reabilitação e a redução de danos à saúde, coordenando ou integrando o cuidado fornecido em outros pontos de atenção.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '13', 'Assistência Obstétrica e Neonatal', 'Conjunto de cuidados ou tratamentos prestados à gestante, parturiente e recém-nascido, por razões obstétricas ou neonatais.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '14', 'Telessaúde', 'Serviços que utilizam tecnologias da informação e comunicação como meio para desenvolver ações de apoio a Atenção à Saúde e de Educação Permanente em Saúde, como fim de realizar apoio diagnóstico, ações educativas, esclarecer dúvidas dos profissionais de saúde e gestores de saúde.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '15', 'Atenção Hematológica e/ou Hemoterápica', 'Conjunto de ações que integram a assistência especializada em coagulopatias e hemoglobinopatias e/ou o conjunto de ações referentes a captação do doador, o ciclo de produção do sangue, testes sorológicos, testes imunohematológicos, distribuição e transfusão de sangue e componentes e demais atividades hemoterápicas.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '16', 'Promoção da Saúde, Prevenção de Doenças e Agravos e Produção do Cuidado', 'Conjunto de ações e serviços de saúde, de caráter individual ou coletivo, compreendendo práticas corporais, artísticas e culturais, práticas integrativas e complementares, atividades físicas, promoção da alimentação saudável ou educação em saúde.', '202308', '01/2017A', '2');
INSERT INTO TB_ATIVIDADE (CO_GRUPO_ATIVIDADE,CO_ATIVIDADE,NO_ATIVIDADE,DS_ATIVIDADE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ('01', '17', 'Imunização', 'Conjunto de ações que objetivam a administração de vacinas para estimulação da resposta imune do hospedeiro, incluindo quaisquer preparações para a profilaxia imunológica ativa.', '202308', '01/2017A', '2');

`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverta a migração se necessário
  }
}
