INSERT INTO TB_CBARA_CATEGORIA (CO_CATERIA,NO_CATERIA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("environment", "Ambiente", "202308", "06/2021A", "2");
INSERT INTO TB_CBARA_CATEGORIA (CO_CATERIA,NO_CATERIA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("food", "Alimento", "202308", "06/2021A", "2");
INSERT INTO TB_CBARA_CATEGORIA (CO_CATERIA,NO_CATERIA,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("medication", "Medicamento", "202308", "06/2021A", "2");
