INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("GISAID sequence accession number", "Sequência GISAID número de registro", "GISAID sequence accession number", "Sequência GISAID número de registro", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Influenza virus A & B & SARS-CoV-2 (COVID-19) RNA panel", "Influenza virus A e B e SARS coronavirus 2 painel RNA", "Influenza virus A & B & SARS-CoV-2 (COVID-19) RNA panel", "Influenza virus A e B e SARS coronavirus 2 painel RNA", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Influenza virus A & Influenza virus B & SARS coronavirus 2 & Respiratory syncytial virus RNA panel", "Influenza virus A e Influenza virus B e SARS Coronavirus 2 e Vírus Sinciciais respiratórios painel de RNA", "Influenza virus A & Influenza virus B & SARS coronavirus 2 & Respiratory syncytial virus RNA panel", "Influenza virus A e Influenza virus B e SARS Coronavirus 2 e Vírus Sinciciais respiratórios painel de RNA", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Influenza virus A & Influenza virus B & SARS coronavirus 2 & SARS-related coronavirus RNA panel", "Influenza virus A e Influenza virus B e SARS coronavirus 2 e  SARS-relacionado coronavirus painel RNA", "Influenza virus A & Influenza virus B & SARS coronavirus 2 & SARS-related coronavirus RNA panel", "Influenza virus A e Influenza virus B e SARS coronavirus 2 e  SARS-relacionado coronavirus painel RNA", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Influenza virus A & Influenza virus B & SARS coronavirus 2 Ag panel", "Vírus Influenza  A e Vírus influenza B e SARS coronavirus 2 painel de Ag", "Influenza virus A & Influenza virus B & SARS coronavirus 2 Ag panel", "Vírus Influenza  A e Vírus influenza B e SARS coronavirus 2 painel de Antígeno", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Influenza virus A & Influenza virus B & SARS coronavirus 2 RNA panel", "Vírus Influenza  A e Vírus influenza B e SARS coronavirus 2 painel de RNA", "Influenza virus A & Influenza virus B & SARS coronavirus 2 RNA panel", "Vírus Influenza  A e Vírus influenza B e SARS coronavirus 2 painel de RNA", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Influenza virus A & Influenza virus B & SARS coronavirus 2 identified", "Influenza virus A e Influenza virus B e SARS coronavirus 2 identificado", "Influenza virus A & Influenza virus B & SARS coronavirus 2 identified", "Influenza virus A e Influenza virus B e SARS coronavirus 2 identificado", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Influenza virus A & Influenza virus B & SARS coronavirus+SARS coronavirus 2 Ag panel", "Influenza virus A e Influenza virus B e SARS coronavirus+SARS Coronavirus 2 painel de Ag.", "Influenza virus A & Influenza virus B & SARS coronavirus+SARS coronavirus 2 Ag panel", "Influenza virus A e Influenza virus B e SARS coronavirus+SARS Coronavirus 2 painel de Antígenos", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Monkeypox virus DNA", "Vírus Varíola dos Macacos DNA", "Monkeypox virus DNA", "Vírus Varíola dos Macacos DNA", "202308", "09/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Orf virus DNA", "Vírus Orf DNA", "Orf virus DNA", "Vírus Orf DNA", "202308", "09/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Orthopoxvirus Ab.IgG", "Orthopoxvirus Anticorpos IgG", "Orthopoxvirus Ab.IgG", "Orthopoxvirus Anticorpos IgG", "202308", "09/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Orthopoxvirus Ab.IgM", "Orthopoxvirus Anticorpos IgM", "Orthopoxvirus Ab.IgM", "Orthopoxvirus Anticorpos IgM", "202308", "09/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Orthopoxvirus DNA", "Orthopoxvirus DNA", "Orthopoxvirus DNA", "Orthopoxvirus DNA", "202308", "09/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Orthopoxvirus IgG & IgM Ab panel", "Orthopoxvirus IgG e IgM painel de Anticorposs", "Orthopoxvirus IgG & IgM Ab panel", "Orthopoxvirus IgG & IgM painel de Anticorpos", "202308", "09/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Orthopoxvirus.non-variola DNA", "Orthopoxvirus não-varíola DNA", "Orthopoxvirus.non-variola DNA", "Orthopoxvirus não-varíola DNA", "202308", "09/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Parapoxvirus DNA", "Parapoxvirus DNA", "Parapoxvirus DNA", "Parapoxvirus DNA", "202308", "09/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Percent neutralization by SARS coronavirus 2 spike  protein RBD Ab.neut", "Percentual de neutralização por SARS coronavirus 2 proteína spike Domínio de Ligação ao RNA Anticorpos neutralizantes", "Percent neutralization by SARS coronavirus 2 spike protein RBD Ab.neut", "Percentual de neutralização por SARS coronavirus 2 proteína spike
Domínio de Ligação ao RNA Anticorpos neutralizantes", "202308", "10/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Pseudocowpox virus DNA", "Vírus da pseudovaríola DNA", "Pseudocowpox virus DNA", "Vírus da pseudovaríola DNA", "202308", "09/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2", "SARS coronavirus 2", "SARS coronavirus 2", "SARS coronavirus 2", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 & SARS-related coronavirus RNA panel", "SARS coronavirus 2 e SARS-relacionado coronavirus painel RNA", "SARS coronavirus 2 & SARS-related coronavirus RNA panel", "SARS coronavirus 2 e SARS-relacionado coronavirus painel RNA", "202308", "08/2021B", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Ab", "SARS coronavirus 2 Ac", "SARS coronavirus 2 Ab", "SARS coronavirus 2 Anticorpos", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Ab panel", "SARS coronavirus 2 painel Ac", "SARS coronavirus 2 Ab panel", "SARS coronavirus 2 painel Anicorpos", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Ab. IgG + IgM", "SARS coronavirus 2 Ac. IgG + IgM", "SARS coronavirus 2 Ab. IgG + IgM", "SARS coronavirus 2 IgG + IgM Anticorpos", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Ab.IgA", "SARS coronavirus 2 Ac.IgA", "SARS coronavirus 2 Ab.IgA", "SARS coronavirus 2 IgA Anticorpos", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Ab.IgA+IgM", "SARS coronavirus 2 Ac.IgA+IgM", "SARS coronavirus 2 Ab.IgA+IgM", "SARS coronavirus 2 IgA + IgM Anticorpos", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Ab.IgG", "SARS coronavirus 2 Ac.IgG", "SARS coronavirus 2 Ab.IgG", "SARS coronavirus 2 IgG Anticorpos", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Ab.IgM", "SARS coronavirus 2 Ac.IgM", "SARS coronavirus 2 Ab.IgM", "SARS coronavirus 2 IgM Anticorpos", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Ab.neut", "SARS coronavirus 2 Ac.neut.", "SARS coronavirus 2 Ab.neut", "SARS coronavirus 2 Anticorpos neutralização", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Ag", "SARS coronavirus 2 Ag", "SARS coronavirus 2 Ag", "SARS coronavirus 2 Antígenos", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 E gene", "SARS Coronavirus 2 gene E", "SARS coronavirus 2 E gene", "SARS coronavirus gene E", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 M gene", "SARS coronavirus 2 gene M", "SARS coronavirus 2 M gene", "SARS coronavirus 2 gene M", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 N gene", "SARS coronavirus 2 gene N", "SARS coronavirus 2 N gene", "SARS coronavirus gene N", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 Nsp2 gene", "SARS coronavirus 2 gene Nsp2", "SARS coronavirus 2 Nsp2 gene", "SARS coronavirus 2 gene Nsp2", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 ORF1a region", "SARS coronavirus 2 ORF1a região", "SARS coronavirus 2 ORF1a region", "SARS coronavirus 2 ORF1a região", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 ORF1ab region", "SARS coronavirus 2 Fases de leitura aberta-1 (ORF1) Anticorpos região", "SARS coronavirus 2 ORF1ab region", "SARS coronavirus 2 Fases de leitura aberta-1 (ORF1) Anticorpos região", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 ORF1b region", "SARS coronavirus 2 ORF1b região", "SARS coronavirus 2 ORF1b region", "SARS coronavirus 2 ORF1b região", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 RNA", "SARS coronavirus 2 RNA", "SARS coronavirus 2 RNA", "SARS coronavirus 2 RNA", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 RNA panel", "SARS coronavirus 2 painel RNA", "SARS coronavirus 2 RNA panel", "SARS coronavirus 2 painel RNA", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 RdRp gene", "SARS coronavirus 2 gene RdRp", "SARS coronavirus 2 RdRp gene", "SARS coronavirus 2 gene RdRp", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 RdRp gene mutation detected", "SARS coronavirus 2 gene RdRp mutação detectada", "SARS coronavirus 2 RdRp gene mutation detected", "SARS coronavirus 2 gene RdRp mutação detectada", "202308", "01/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 S gene", "SARS coronavirus 2 gene S", "SARS coronavirus 2 S gene", "SARS coronavirus 2 gene S", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 S gene mutation", "SARS Coronavirus 2 gene S mutação", "SARS coronavirus 2 S gene mutation", "SARS Coronavirus 2 gene S mutação", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 S gene mutation detected", "SARS Coronavirus 2 gene S mutação detectada", "SARS coronavirus 2 S gene mutation detected", "SARS Coronavirus 2 gene S mutação detectada", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 clade", "SARS coronavirus 2 Clade", "SARS coronavirus 2 clade", "SARS coronavirus nomenclatura Clade", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 lineage", "SARS coronavirus 2 linhagem", "SARS coronavirus 2 lineage", "SARS coronavirus 2 linhagem", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 nucleocapsid protein Ab.IgG", "SARS coronavirus 2 proteína do nucleocapsídeo IgG Ac", "SARS coronavirus 2 nucleocapsid protein Ab.IgG", "SARS coronavirus 2 proteína do nucleocapsídeo IgG Anticorpos", "202308", "01/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 sequencing & identification panel", "SARS coronavirus 2 sequenciamento e painel de identificação", "SARS coronavirus 2 sequencing & identification panel", "SARS coronavirus 2 sequenciamento e painel de identificação", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 specific TCRB gene rearrangements", "SARS coronavirus 2 rearranjos específicos de Genes Codificadores da Cadeia beta de Receptores de Linfócitos T", "SARS coronavirus 2 specific TCRB gene rearrangements", "SARS coronavirus 2 rearranjos específicos de Genes Codificadores da Cadeia beta de Receptores de Linfócitos T", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 spike & nucleocapsid protein stimulated gamma interferon panel", "SARS coronavirus 2 proteína spike e do nucleocapsídeo IgG Ac painel de interferon gama estimulado", "SARS coronavirus 2 spike and nucleocapsid protein 
stimulated gamma interferon panel", "SARS coronavirus 2 proteína spike e proteína do nucleocapsídeo IgG Anticorpos painel de interferon gama estimulado", "202308", "01/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 spike protein Ab.IgG", "SARS coronavirus 2 proteína spike IgG Ac", "SARS coronavirus 2 spike protein Ab.IgG", "SARS coronavirus 2 proteína spike IgG Anticorpos", "202308", "01/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 spike protein RBD Ab.neut", "SARS coronavirus 2 proteína S Domínio de Ligação ao RNA Anticorpos neutralizante", "SARS coronavirus 2 spike protein RBD Ab.neut", "SARS coronavirus 2 proteína S Domínio de Ligação ao RNA Anticorpos neutralizante", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 stimulated gamma interferon", "SARS coronavirus 2 interferon gama estimulado", "SARS coronavirus 2 stimulated gamma interferon", "SARS coronavirus 2 interferon gama estimulado", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 stimulated gamma interferon  release by Helper (CD4+) T-cells^^corrected for background", "SARS coronavirus 2 Interferon gama estimulado liberação por  células T auxiliares (CD4+) corrigidos para fundo", "SARS coronavirus 2 stimulated gamma interferon 
release by Helper (CD4+) T-cells^^corrected for background", "SARS coronavirus 2 Interferon gama estimulado liberação por 
células T auxiliares (CD4+) corrigidos para fundo", "202308", "10/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 stimulated gamma interferon  release by lymphocytes^^corrected for background", "SARS coronavirus 2 Interferon gama estimulado liberação por  linfócitos^^corrigidos para fundo", "SARS coronavirus 2 stimulated gamma interferon 
release by lymphocytes^^corrected for background", "SARS coronavirus 2 Interferon gama estimulado liberação por 
linfócitos^^corrigidos para fundo", "202308", "10/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 stimulated gamma interferon panel", "SARS coronavirus 2 painel de interferon gama estimulado", "SARS coronavirus 2 stimulated gamma interferon panel", "SARS coronavirus 2 painel de interferon gama estimulado", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 stimulated gamma interferon release by T-cells", "SARS coronavirus 2 interferon gama estimulado liberação por células T", "SARS coronavirus 2 stimulated gamma interferon release by T-cells", "SARS coronavirus 2 interferon gama estimulado liberação por células T", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 stimulated gamma interferon release by T-cells ^ ^ corrected for background", "SARS coronavirus 2 interferon gama estimulado liberação por células T ^ ^ corrigido para fundo", "SARS coronavirus 2 stimulated gamma interferon release by T-cells ^ ^ corrected for background", "SARS coronavirus 2 interferon gama estimulado liberação por células T ^ ^ corrigido para fundo", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 stimulated gamma interferon release by T-cells. Nucleocapsid Ag spot count^^corrected for background", "SARS coronavirus 2 interferon gama estimulado liberação por células T. Nucleocapsídeos Ag área de contagem ^^corrigido para fundo", "SARS coronavirus 2 stimulated gamma interferon 
release by T-cells. Nucleocapsid Ag spot count^^corrected for background"", "SARS coronavirus 2 interferon gama estimulado liberação por células T. Nucleocapsídeos Antígenos área de contagem^^corrigido para fundo", "202308", "01/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 stimulated gamma interferon release by T-cells. Spike Ag spot count^^corrected for background", "SARS coronavirus 2 interferon gama estimulado liberação por células T. Spike Ag ^^corrigido para fundo", "SARS coronavirus 2 stimulated gamma interferon release by T-cells. Spike Ag spot count^^corrected for background", "SARS coronavirus 2 interferon gama estimulado liberação por células T. Spike Antígenos área de contagem^^corrigido para fundo", "202308", "01/2022A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 variant", "SARS coronavirus 2 variant", "SARS coronavirus 2 variant", "SARS coronavirus 2 variant", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 variant interpretation", "SARS coronavirus variante interpretação", "SARS coronavirus 2 variant interpretation", "SARS coronavirus variante interpretação", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus 2 whole genome", "SARS coronavirus 2 genoma isolado", "SARS coronavirus 2 whole genome", "SARS coronavirus 2 genoma isolado", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS coronavirus+SARS coronavirus 2 Ag", "SARS coronavirus+SARS coronavirus 2 Ag", "SARS coronavirus+SARS coronavirus 2 Ag", "SARS coronavirus+SARS coronavirus 2 Antígeno", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS-like coronavirus N gene", "SARS (como) coronavirus gene N", "SARS-like coronavirus N gene", "SARS (como) coronavirus gene N", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS-related coronavirus E gene", "SARS-related coronavirus gene E", "SARS-related coronavirus E gene", "SARS-related coronavirus gene E", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS-related coronavirus N gene", "SARS- relacionado coronavirus gene N", "SARS-related coronavirus N gene", "SARS- relacionado coronavirus gene N", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS-related coronavirus RNA", "SARS-relacionado coronavirus RNA", "SARS-related coronavirus RNA", "SARS-relacionado coronavirus RNA", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("SARS-related coronavirus+MERS coronavirus RNA", "SARS-relacionadocoronavirus+ MERS coronavirus RNA", "SARS-related coronavirus+MERS coronavirus RNA", "SARS-relacionadocoronavirus+MERS coronavirus RNA", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("Sequencing study identifier", "Identificador de estudo de sequencimento", "Sequencing study identifier", "Identificador de estudo de sequencimento", "202308", "08/2021A", "2");
INSERT INTO TB_LOINC_COMPONENTE (DS_ABREVIATURA_INGLES,DS_ABREVIATURA,NO_COMPONENTE_INGLES,NO_COMPONENTE,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("West African monkeypox virus DNA", "Vírus Varíola dos Macacos da África Ocidental DNA", "West African monkeypox virus DNA", "Vírus Varíola dos Macacos da África Ocidental DNA", "202308", "09/2022A", "2");
