INSERT INTO TB_TIPO_FINANCIAMENTO (CO_TIPO_FINANCIAMENTO,NO_TIPO_FINANCIAMENTO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO ) VALUES ("02", "Assistência Farmacêutica", "202308", "01/2017A", "2");
INSERT INTO TB_TIPO_FINANCIAMENTO (CO_TIPO_FINANCIAMENTO,NO_TIPO_FINANCIAMENTO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("04", "Fundo de Ações Estratégicas e Compensações (FAEC)", "202308", "01/2017A", "2");
INSERT INTO TB_TIPO_FINANCIAMENTO (CO_TIPO_FINANCIAMENTO,NO_TIPO_FINANCIAMENTO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("05", "Incentivo - MAC", "202308", "01/2017A", "2");
INSERT INTO TB_TIPO_FINANCIAMENTO (CO_TIPO_FINANCIAMENTO,NO_TIPO_FINANCIAMENTO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("06", "Média e Alta Complexidade (MAC)", "202308", "01/2017A", "2");
INSERT INTO TB_TIPO_FINANCIAMENTO (CO_TIPO_FINANCIAMENTO,NO_TIPO_FINANCIAMENTO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("07", "Vigilância em Saúde", "202308", "01/2017A", "2");
INSERT INTO TB_TIPO_FINANCIAMENTO (CO_TIPO_FINANCIAMENTO,NO_TIPO_FINANCIAMENTO,DT_COMPETENCIA,CO_VERSAO,ST_ACAO) VALUES ("08", "Gestão do SUS", "202308", "01/2017A", "2");
